# Generated by Django 4.1.7 on 2023-04-12 03:46

import autoslug.fields
from django.db import migrations
import lk.models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truba',
            name='trump_url',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, null=True, populate_from=lk.models.instance_slug, slugify=lk.models.slugify_value, unique=True, verbose_name='trump_url'),
        ),
    ]
