# Generated by Django 4.1.7 on 2023-04-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_alter_truba_trump_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truba',
            old_name='trump_url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='truba',
            name='def_1_compl_rem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Работы выполнены'),
        ),
    ]
